server:
   port: 10000
spring:
   messages:
      encoding: UTF-8
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MariaDB103Dialect
      hibernate:
         ddl-auto: update
      show-sql: true
   datasource:
      username: root
      password: root
      url: jdbc:mariadb://localhost:3306/entrega?createDatabaseIfNotExist=true
      driverClassName: org.mariadb.jdbc.Driver

   # RabbitMQ
   rabbitmq:
      host: localhost
      port: 5672
      username: root
      password: root
      publisher-confirm-type: correlated
      publisher-returns: true
      
   # Kafka
   kafka:
      producer:
         bootstrap-servers: 127.0.0.1:9092
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.apache.kafka.common.serialization.StringSerializer
         group-id: group_id
   
   mvc:
      pathmatch:
         matching-strategy: ant_path_matcher
   
# Kafka
topic:
   name:
      producer: pagamentos
      
auto:
   create:
      topics:
         enable: true