server:
   port: 10000
spring:
   messages:
      encoding: UTF-8
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MariaDB103Dialect
      hibernate:
         ddl-auto: update
      show-sql: true
   datasource:
      username: root
      password: root
      url: jdbc:mariadb://localhost:3306/entrega?createDatabaseIfNotExist=true
      driverClassName: org.mariadb.jdbc.Driver
   rabbitmq:
      host: localhost
      port: 5672
      username: root
      password: root
      publisher-confirm-type: correlated
      publisher-returns: true
   mvc:
      pathmatch:
         matching-strategy: ant_path_matcher
   