server:
   port: 10000
spring:
   messages:
      encoding: UTF-8
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
   h2:
      console:
         enabled: true
         path: /h2
   datasource:
      username: admin
      password: null
      url: jdbc:h2:file:./database/database
      driverClassName: org.h2.Driver
   mvc:
      pathmatch:
         matching-strategy: ant_path_matcher
   